function init(self)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("clicked") then 
		msg.post("/Clicks#ClickPoints", "clicked")
		go.set("#clickSprite","scale", vmath.vector3(1,1,1))
	elseif message_id == hash("clicking") then 
		go.set("#clickSprite","scale", vmath.vector3(1.5,1.5,1))
	end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
